### ISSUE TITLE
Question About Parameter Passing in the main Function

### ISSUE THREAD

**Issue by 0sidewalkenforcer0** [seucoin/unKR#1]
It seems like there's some hard coding here：
![651728589304_ pic](https://github.com/user-attachments/assets/202438d0-577d-4991-b548-3baebd3765f2)
If the command-line arguments are being passed in correctly?:
![671728589304_ pic](https://github.com/user-attachments/assets/72856c0a-46b1-461b-99a8-15f4de288d6f)

**Comment by seucoin** [comment]
Thank you for bringing this issue to our attention.  You're right, the problem you've described does exist.  And it has been addressed and resolved in our latest version.

To benefit from the fix, please update to the latest version of our project.  

If you continue to experience any issues after updating, feel free to open another issue or reach out for further assistance.

Thanks again for your contribution to improving our project!
