### ISSUE TITLE
Inconsistent Parameter Passing in `litmodel_class` for Different Models

### ISSUE THREAD

**Issue by 0sidewalkenforcer0** [seucoin/unKR#2]
Thank you for resolving the previous issue. However, as the config is now soft-coded, there is another problem: In `main.py`, line 41, the `litmodel_class` receives three parameters for models like `GMUCLitModel(model, train_sampler, args)`, but only two parameters for others (e.g., `UKGElitModel(model, args)`). Could you please make this parameter passing consistent across all models?
<img width="610" alt="image" src="https://github.com/user-attachments/assets/a499d2b7-3ffe-454c-95ac-d17b4e422b73">
<img width="556" alt="image" src="https://github.com/user-attachments/assets/de4300d8-a764-422c-97fe-64f509733f1c">
<img width="689" alt="image" src="https://github.com/user-attachments/assets/e45d086f-6b76-4469-9b04-1dba9ee29137">

**Comment by CodeSlogan** [comment]
To address your concerns more specifically, you might find the scripts designed for different models located in the demo folder quite helpful. These scripts are tailored to various models and can provide targeted solutions to the issues you've raised.
![image](https://github.com/user-attachments/assets/d5246973-40a9-4796-af95-badafd61978f)

Feel free to explore the demo folder and see if any of the provided scripts meet your needs. If you have any further questions or need additional assistance, please don't hesitate to ask.

**Comment by CodeSlogan** [comment]
To address your concerns more specifically, you might find the scripts designed for different models located in the demo folder quite helpful. These scripts are tailored to various models and can provide targeted solutions to the issues you've raised.

Feel free to explore the demo folder and see if any of the provided scripts meet your needs. If you have any further questions or need additional assistance, please don't hesitate to ask.
